# Generated by Django 5.2.8 on 2026-01-29 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('business_email', models.EmailField(max_length=254)),
                ('region', models.CharField(choices=[('arusha', 'Arusha'), ('dar_es_salaam', 'Dar es Salaam'), ('dodoma', 'Dodoma'), ('geita', 'Geita'), ('iringa', 'Iringa'), ('kagera', 'Kagera'), ('katavi', 'Katavi'), ('kigoma', 'Kigoma'), ('kilimanjaro', 'Kilimanjaro'), ('lindi', 'Lindi'), ('manyara', 'Manyara'), ('mara', 'Mara'), ('mbeya', 'Mbeya'), ('morogoro', 'Morogoro'), ('mtwara', 'Mtwara'), ('mwanza', 'Mwanza'), ('njombe', 'Njombe'), ('pemba_north', 'Pemba North'), ('pemba_south', 'Pemba South'), ('pwani', 'Pwani'), ('rukwa', 'Rukwa'), ('ruvuma', 'Ruvuma'), ('shinyanga', 'Shinyanga'), ('simiyu', 'Simiyu'), ('singida', 'Singida'), ('songwe', 'Songwe'), ('tabora', 'Tabora'), ('tanga', 'Tanga'), ('unguja_north', 'Unguja North'), ('unguja_south', 'Unguja South'), ('zanzibar_west', 'Zanzibar West')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
