# Generated by Django 5.2.8 on 2026-02-07 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_shoplocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopLocation',
        ),
    ]
