# Generated by Django 5.2.8 on 2026-02-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluesoko', '0002_shoprating'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
